### ISSUE TITLE
List Command Bug Report [KH]

### ISSUE THREAD

**Issue by yongkheehou** [AY2425S1-CS2103T-T16-2/tp#182]
# Summary

refer to Google Doc link below for the bugs reported:
- https://docs.google.com/document/d/1xLImBNe5xsb9w7r5LaawXEcA-O9AiYJGH-Ac8NP512M/edit?tab=t.0#bookmark=id.ceqfv451mjxx

**Comment by apollo-tan** [comment]
Basically deal with all the UG and DG issues here

- [x] Update User Stories of UG to include listing meetings and clients
- [x] Update Use case: UC1 to be clear that you can list buyers and sellers separately, and the possibility of typing an invalid key in extensions. Maybe like if there are no data in ClientGrid, then also return nothing.
- [ ] add for their own command the instructions for manual testing
