### ISSUE TITLE
Bug for addseller command

### ISSUE THREAD

**Issue by thony-ui** [AY2425S1-CS2103T-T16-2/tp#190]
#### Test Inputs:
1. `addseller   p/83234567    n/bob      e/test@gmai.com`
2. `addseller n/bob p/83234567      e/test@gmai.com`

#### Expected Outputs:
1. `New seller added: SELLER; bob; Phone: 83234567; Email: test@gmail.com`
   
#### Observed Outputs:
1. `New seller added: SELLER; bob; Phone: 81234567; Email: test@gmail.com`
2. `New seller added: SELLER; bob; Phone: 83234567; Email: test@gmail.com`

#### Notes:
- **Spacing Bug:** There is inconsistent spacing between command parameters. Consider standardizing to enforce only one space between each command to improve consistency.
- **Order of Parameters:** The command seems flexible with parameter ordering, which may not be a bug but worth noting for consistent usage.

**Comment by yongkheehou** [comment]
fixed together with `addbuyer` command
