### ISSUE TITLE
Bug detection for deletemeeting command

### ISSUE THREAD

**Issue by thony-ui** [AY2425S1-CS2103T-T16-2/tp#202]
### Issue with `deletemeeting` Command

1. **Incorrect Error Message for Date Format**  
   - **Command:** `deletemeeting mt/test d/01-01-2025 a/sdfasdf`
   - **Current Error Message:** "Meeting dates should be in the format `dd-MM-yyyy` and must be a valid date."
   - **Expected Error Message:** The error should relate to the incorrect number of parameters provided rather than an issue with the date format.

2. **Incorrect Error Message for Duplicate Prefixes**  
   - **Command:** `deletemeeting mt/123 d/01-01-2025 MT/123`
   - **Current Error Message:** "Meeting dates should be in the format `dd-MM-yyyy` and must be a valid date."
   - **Expected Error Message:** An error indicating that prefixes are duplicated (`mt/` and `MT/`), not an error regarding date format.

### Suggested Solution
This issue of checking for correct parameters and avoiding duplicate prefixes should be applied to **all commands**. We should ensure that:
- **Parameter Count**: The command validates the number of parameters before other validations.
- **Prefix Duplication**: The command checks for duplicate prefixes and throws an error if any are found.

Consider adding this validation logic in a central location applicable to all commands.

**Comment by yongkheehou** [comment]
fixed in pull #226
