### ISSUE TITLE
[Bug] AddBuyer Command Restriction and Error Message

### ISSUE THREAD

**Issue by jolwnn** [AY2425S1-CS2103T-T16-2/tp#219]
addbuyer n/test p/9876       4321 e/test        @gmail.com

addbuyer n/test p/98764321 e/test        @gmail.com

Not specified in the restriction description, may be important as users are used to putting spaces like 9876 4321 for phone number

This buyer already exists in the address book. 

Suggestion for this error message to be more specific eg. Buyer with this phone number exists already, because we only identify by phone no. User may be confused why a buyer of different name but same phone number triggers error.

**Comment by yongkheehou** [comment]
fixed in pull #203
