### ISSUE TITLE
Deduplicate Email Addresses

### ISSUE THREAD

**Issue by yongkheehou** [AY2425S1-CS2103T-T16-2/tp#263]
Currently, we can add a seller with the same email address but a DIFFERENT phone number as an existing buyer. This should not make sense since a client's email should be unique to him. 

This issue fixes this issue by ensuring that the email field specified in `addbuyer` and `addseller` are "deduplicated" following this logic:

# for `addbuyer`
```
No duplicate emails are allowed. Duplicate emails are detected if
1. there is a buyer with the same email already in the client book.
2. there is a seller with the same email but a different phone number in the client book. Having the same email address as an existing seller with a different phone number is not allowed as emails should be unique to a client.
```

catching a duplicate email in `addbuyer` because there is a seller (client number 5) with a different phone number but the same email
<img width="1512" alt="Screenshot 2024-11-07 at 2 17 42 PM" src="https://github.com/user-attachments/assets/d6745623-d9c9-4069-ae54-64f9c35586da">

# for `addseller`
```
**Duplicate Emails**: No duplicate emails are allowed, following the same logic as the `addbuyer` command:
1. A seller cannot share the same email as another seller.
2. A seller cannot have the same email as a buyer with a different phone number. Email uniqueness is enforced per client.
```

catching a duplicate email in `addseller` because there is a buyer (client number 6) with a different phone number but the same email
<img width="1512" alt="Screenshot 2024-11-07 at 2 17 10 PM" src="https://github.com/user-attachments/assets/6e7dd266-31bc-4490-b184-6aad287dadba">

**Comment by apollo-tan** [comment]
Good catch! I think the proposed fix makes sense!
