### ISSUE TITLE
[PE-D][Tester B] Inflexibility of storing address of properties

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#296]
Unit Number may not always follow the XX-XXX format

It may be possible that different `LANDED` properties have the same postal code. For instance, some landed properties may have the same postal code, but are marked by different unit number e.g. "166A", "166B". It should not be assumed that their unit number is #00-000

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: gabriellegtw/ped#5

**Comment by Virusrwj223** [comment]
May be V1.6 candidate.
