### ISSUE TITLE
[PE-D][Tester C] Unable to add buyer names with hyphens

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-2/tp#297]
## Detail: 
I am unable to add buyer names with hyphens such as Ong-Lai. 

## Screenshots:

![image.png](https://raw.githubusercontent.com/hweinian/ped/main/files/0464831f-4184-4575-8b55-ca45599fa55f.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: hweinian/ped#4

**Comment by yongkheehou** [comment]
let's specify a workaround for this in the UG instead => replace hyphens with spaces?

or we can put it as planned enhancements
