### ISSUE TITLE
[PE-D][Tester C] Incorrect notation in logic component in developer guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#301]
## Detail:
Association labels should not be use double angle brackets like `<<call>>`

## Screenshot:

![image.png](https://raw.githubusercontent.com/hweinian/ped/main/files/f91c5273-bf61-4bf5-a98b-4f69e594b966.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hweinian/ped#7

**Comment by yongkheehou** [comment]
is this true? potentially an inherited bug from AB3?
