### ISSUE TITLE
[PE-D][Tester B] Delete Meeting - Unsuccessful deletion

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#311]
Although the name and date is the same, it does not successfully delete the meeting.

Perhaps in the string matching cases of the words can be ignored

![image.png](https://raw.githubusercontent.com/gabriellegtw/ped/main/files/06a3e254-6a08-4fce-b377-f486a386ac66.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: gabriellegtw/ped#10

**Comment by jolwnn** [comment]
Specified in UG the reasoning behind enabling case sensitivity for meeting titles
