### ISSUE TITLE
[PE-D][Tester E] Inaccurate logic for filterproperty

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#316]
Input
![Screenshot 2024-11-08 at 5.07.43 PM.png](https://raw.githubusercontent.com/rynlwhh/ped/main/files/ab675bf8-1657-4e37-a25d-cc64064d317f.png)
Outcome
![Screenshot 2024-11-08 at 5.07.47 PM.png](https://raw.githubusercontent.com/rynlwhh/ped/main/files/dfb9f425-acf5-45af-979f-157fdd12c448.png)

When I input the following command for filter property, where the upper bound is lower than the lower bound, it should give an error as it is logically not possible, however the command still goes through

Proposed solution: To give an error message when the MATCHINGPRICE for gte is more than lte

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: rynlwhh/ped#5

**Comment by Virusrwj223** [comment]
Result outputted is correct as price cannot be both less than and greater than the other. 

Can include in warning in same place as `Important` that mathematical correctness lies on user.
