### ISSUE TITLE
[PE-D][Tester A] Difficulty in deciphering command keyword and mixing up for filterproperty 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#318]
The option of giving lower limit and upper limit is great for filtering properties but I think it would be better to explain what gte and lte is in this case. I was trying a small number as input for lte and a big number for gte and got an error but was unsure on what I was doing wrong. I think would be better to explain so that users know what the keywords in the command mean and their intentions as the keywords are considered optional in this command and hence there's the possibility of reversing the order. 

![image.png](https://raw.githubusercontent.com/SKarthikeyan28/ped/main/files/28d4e2c7-6bcc-4ceb-84c8-a89a26767e75.png)

![image.png](https://raw.githubusercontent.com/SKarthikeyan28/ped/main/files/b084f31b-388c-4667-ba88-aa232f866eab.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: SKarthikeyan28/ped#4

**Comment by thony-ui** [comment]
Yea so we mention what is LTE OR GTE before giving the short form in the same def box as the Matching Price
