### ISSUE TITLE
[PE-D][Tester C] Unable to add already attended meetings

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#319]
## Detail:
User may have already attended a meeting, but he/she is am unable to record it into the address book for record logging purposes.

## Steps to reproduce:
addmeeting mt/helloitsme d/23-02-2024 bp/99999999 sp/99999999 t/hdb c/000000

## Suggested fix:
Remove validation that checks if the meeting is scheduled today or in the future. 

## Screenshot:

![image.png](https://raw.githubusercontent.com/hweinian/ped/main/files/4304c46c-3828-4f65-8e34-32c5147a9fc8.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hweinian/ped#15

**Comment by jolwnn** [comment]
This is a design choice and as we would like our app to offer active input validation to help the user. But the other POV is not wrong, we can consider relaxing this validation in future iterations of the app.
