### ISSUE TITLE
[PE-D][Tester B] "Incomplete" filter feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-2/tp#322]
Searching "Yeoh" would not find "Alex Yeoh". Noted from the UG that this is intentional behaviour but may not serve users well if they have a buyer with a distinct surname and want to find them via that 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: gabriellegtw/ped#14

**Comment by thony-ui** [comment]
This should be a feature.NotInScope
