### ISSUE TITLE
[PE-D][Tester B] User Guide - Some terms may be hard to understand for the target audience

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-2/tp#327]
Considering that this is for a largely non-technical audience, perhaps a link can be given to the download of Java 17, as well as a very short explanation on how to open the command terminal

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: gabriellegtw/ped#15

**Comment by Virusrwj223** [comment]
Start a glossary in the UG
