### ISSUE TITLE
[PE-D][Tester E] Example commands in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-2/tp#328]
![Screenshot 2024-11-08 at 5.42.40 PM.png](https://raw.githubusercontent.com/rynlwhh/ped/main/files/94004997-8feb-4401-a22c-129d5bdfd262.png)

This is a bit nitpicky but the example commands in the quick start section of the UG should contain each feature available, it is missing the seller and meeting functions. 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: rynlwhh/ped#8

**Comment by apollo-tan** [comment]
Thank you for that suggestion! However, I believe we did mention "**some** example commands you can try" so we would like to leave this portion as just "samples" they could try, but the full command usages will be presented in the feature list below. This is also to prevent cluttering up the "Quick Start" as after all, it's meant for them to "quick start".
