### ISSUE TITLE
[PE-D][Tester B] User Guide - No mention of special case

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#330]
It is possible for a buyer and seller to have different name AND email but same phone number but this specific case is not in the UG

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: gabriellegtw/ped#17

**Comment by yongkheehou** [comment]
<img width="1512" alt="Screenshot 2024-11-10 at 10 27 01 AM" src="https://github.com/user-attachments/assets/3926f09d-d19f-47b8-9065-b9c4827753e5">

I have added a buyer with this command already
`addbuyer n/timmy p/91234561 e/timmy@gmail.com`

In the screenshot, I tried adding a seller with a different name and different email but with the same phone number `addseller n/timmy2 p/91234561 e/timmy2@gmail.com`.
As demonstrated, it is not possible to do so
