### ISSUE TITLE
[PE-D][Tester D] Wrong name in log; still shows addressbook

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-2/tp#338]
![image.png](https://raw.githubusercontent.com/kimxw/ped/main/files/2f40bff9-1c97-493a-9221-7ea70b61fe40.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: kimxw/ped#2

**Comment by Virusrwj223** [comment]
Need to resolve

**Comment by yongkheehou** [comment]
log file: java/seedu/address/commons/core/LogsCenter.java

log messages: java/seedu/address/MainApp.java

cand do ctrl + f to find other instances of address book
