### ISSUE TITLE
[PE-D][Tester D] when the JSON file is updated with a bid value of 1,000,000 (thousand) and saved, and app is reopened, all the properties disappear 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T16-2/tp#341]
when the JSON file is updated with a bid value of 1,000,000 (thousand) and saved, and app is reopened, all the properties disappear when list k/properties is typed

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kimxw/ped#5

**Comment by Virusrwj223** [comment]
Possible change in UG -> Last part also include if it violates any existing restrictions, it also discards.

**Comment by jolwnn** [comment]
for all json files
