### ISSUE TITLE
Standardize DG Requirements Section

### ISSUE THREAD

**Issue by yongkheehou** [AY2425S1-CS2103T-T16-2/tp#46]
After completing the features, standardize the following in the Requirements section of the Appendix
- granularity of the extensions (error in command name + error in parsing fields + no/ duplicate entry in database)
- language and style of writing the requirements
- remove overlapping use cases and reference them directly

**Comment by Virusrwj223** [comment]
- [x] Standardise Acknowledgements in Home page and DG
- [x] Ensure that code links are removed
